### ISSUE TITLE
Duplicate records in GB, GB-0242576

### ISSUE THREAD

**Issue by shahmanash** [mossnisse/Virtuella-Herbariet#1]
There seem to be 2 records for the same catalogue number in data from Herbarium GB,  
GB-0242576

http://herbarium.emg.umu.se/list.php?Group=*&Subgroup=*&Genus=*&Species=*&SspVarForm=*&HybridName=*&Continent=*&Country=*&Province=*&District=*&InstitutionCode=GB&AccessionNo=GB-0242576&SmartCollector=*&Collectornumber=*&YearStart=*&YearEnd=*&Year=*&Month=*&Day=*&Original_name=*&Original_text=*&Image=*&Type_status=*&Basionym=*&Svenskt_namn=*&Lan=*&Kommun=*&search=Search

Please check.

**Comment by mossnisse** [comment]
It's an Issue with the data from GB not the code or data in VH
