### ISSUE TITLE
Duplicate records in UPS, B-034029

### ISSUE THREAD

**Issue by shahmanash** [mossnisse/Virtuella-Herbariet#2]
There seem to be 2 records for the same catalogue number in data from Herbarium UPS,
B-034029

http://herbarium.emg.umu.se/list.php?Group=*&Subgroup=*&Genus=*&Species=*&SspVarForm=*&HybridName=*&Continent=*&Country=*&Province=*&District=*&InstitutionCode=UPS&AccessionNo=B-034029&SmartCollector=*&Collectornumber=*&YearStart=*&YearEnd=*&Year=*&Month=*&Day=*&Original_name=*&Original_text=*&Image=*&Type_status=*&Basionym=*&Svenskt_namn=*&Lan=*&Kommun=*&search=Search

Please check

**Comment by mossnisse** [comment]
It's an issue with the data from UPS, Evolutionsmuseet - Uppsala universitet not the code or data in VH
