### ISSUE TITLE
Duplicate records in UME

### ISSUE THREAD

**Issue by shahmanash** [mossnisse/Virtuella-Herbariet#3]
The simple CSV export for UME contains a number of records where the catalogue number is duplicated.
[ume-duplicates.txt](https://github.com/user-attachments/files/17901629/ume-duplicates.txt)

Since catalogue number seem to be the only field that in included in the export files that could possibly be used as primary key it makes is difficult to use the export when there are duplicate records for the same catalogNumber.

**Comment by mossnisse** [comment]
It's an issue with the data from Herbarium UME, not the code or data in VH
